#!/usr/bin/env zsh

## env setup

# input handling (program load)
bf_input="$1"

# alias integer to int for brevity
alias int="integer"

# error printout if program input is blank
blank_printout() {
  print -u2 "Error: no input provided, or input file empty"
  print -u2 "       syntax: bf_run ./input_file"
  print -u2 "               bf_run <input>"
}

# initial blank check
[[ -z "$bf_input" ]] && {
  blank_printout
  return 1
}

# if input is file, read from file and make new input
[[ -f "$bf_input" ]] && {
  bf_input=$(<"$bf_input")
}

# run blank check twice in case file is empty
[[ -z "$bf_input" ]] && {
  blank_printout
  return 1
}

# load zsh/mapfile for streamfile reading
zmodload zsh/mapfile

# if mem_wrap is unset, default to 0 (disabled)
[[ -z "$mem_wrap" ]] && {
  int mem_wrap
}

int dyn_stream

# if streamfile not set, enable dyn_stream
[[ -z "$streamfile" ]] && {
  dyn_stream=1
}

# if b32 not set, default to 8-bit, else use 32-bit
[[ -z "$b32" ]] && {
  b32=255
} || {
  b32=0xffffffff
}

# if b64 flag is set, use 64-bit cells (requires libalm)
[[ ! -z "$b64" ]] && {
  int b64=1
  # locate libalm
  [[ -f /usr/lib/libalm/libalm ]] && {
    source /usr/lib/libalm/libalm
  } || [[ -f $HOME/.libalm/libalm ]] && {
    source $HOME/.libalm/libalm
  } || {
    which git &> /dev/null && {
      git clone https://github.com/m1ndflay3r/libalm $HOME/.libalm
      source $HOME/.libalm/libalm
    } || {
      return 1
    }
  }
} || {
  int b64
}

# array declarations
typeset -A tape # use associative array for tape as brainfuck expects 0-index
typeset -a loop_stack

# variable declarations
int pointer stream_offset abortflag

# set memory limit to 1048576 (1mb) if undefined
[[ -z "$memlimit" ]] && {
  int memlimit=1048576
# else, set memlimit to 1048576 X memlimit
} || {
  int memlimit=$((1048576*memlimit))
}

# since it's possible to set mem lower than 1mb via setting memlimit to 0<N<1, we add this check
((memlimit<1024)) && {
  print -u2 "Error: memlimit cannot be smaller than 1024 (1kb)"
  return 1
}

## helper functions

# output current cell contents
print_cell() {
  # use %02x to ensure 2 digit hex
  local target=${tape[$pointer]:-0}
  printf "\\x$(printf %02x $target)"
}

# decrease pointer by 1
pointer_decrement() {
  ((pointer==0)) && {
    # since this is emulated memory using arrays, we can semi-safely wrap without risking memory of other processes
    # typically, you should not do this, especially if your bf interpreter is written in a low-level lang
    # hence, it's disabled by default
    ((mem_wrap==1)) && {
      ((pointer=memlimit))
    } || {
      print -u2 "Segmentation Fault"
      ((abortflag++))
    }
  } || {
    ((pointer--))
  }
}

# increase pointer by 1
pointer_increment() {
  ((pointer==memlimit)) && {
    # since this is emulated mem using arrays, we can semi-safely wrap without risking the memory of other processes
    # typically, you should not do this, especially if your bf interpreter is written in a low-level lang
    # hence, it's disabled by default
    ((mem_wrap==1)) && {
      ((pointer=0))
    } || {
      print -u2 "Segmentation Fault"
      ((abortflag++))
    }
  } || {
    ((pointer++))
  }
}

# Note: two versions of both cell_increment and cell_decrement exist, depending on whether b64 is enabled.
# This results in significantly faster execution times at the cost of a slightly longer startup time.

# increment current cell
((b64)) && {
  cell_increment() {
    local -i pointer_out
    hexmask=1 albm $((${tape[$pointer]:-0}+1)) ffffffffffffffff pointer_out # use libalm to apply 64-bit bitmask
    tape[$pointer]=$pointer_out
  }
} || {
  cell_increment() {
    ((tape[$pointer]=(${tape[$pointer]:-0}+1)&$b32)) # use bitmask to keep values within $b32; uninitialized cells are treated as zero
  }
}

# decrement current cell
((b64)) && {
  cell_decrement() {
    local -i pointer_out
    hexmask=1 albm $((${tape[$pointer]:-0}-1)) ffffffffffffffff pointer_out # use libalm to apply 64-bit bitmask
    tape[$pointer]=$pointer_out
  }
} || {
  cell_decrement() {
    ((tape[$pointer]=(${tape[$pointer]:-0}-1)&$b32)) # use bitmask to keep values within $b32; uninitialized cells are treated as zero
  }
}

# read byte from input stream
stream_read() {
  # if dyn_stream enabled
  ((dyn_stream)) && {
    # read a char from user input
    local char
    read -r -s -k1 char
    # conv char to ascii, store in current cell
    tape[$pointer]=$(printf "%d" "'$char")
  } || {
    # while a bit inefficient, this method allows mid-program streamfile modification
    # and is more than fast enough for our purposes
    [[ -f "$streamfile" ]] && {
      local sr_working=${mapfile[$streamfile]:$stream_offset:1}
      ((stream_offset++))
      # if sr_working empty, treat as zero
      [[ -z "$sr_working" ]] && {
        tape[$pointer]=0
      } || {
        # conv sr_working to ascii, store in current cell
        tape[$pointer]=$(printf "%d" "'$sr_working")
      }
    # if file not exist, treat as zero
    } || {
      ((stream_offset++))
      tape[$pointer]=0
    }
  }
}

r_jmp() {
  ((${tape[$pointer]:-0}==0)) && {
  ## jump if zero
    # depth flag keeps track of nested loops
    int depth=1
    # loop repeats while depth >= 1
    while ((depth>0)); do
      # if bf_input empty, we've reached end of program without discovering [
      # which according to brainfuck spec we must treat as a fatal error
      [[ -z "$bf_input" ]] && {
        print -u2 "FATAL: Unbalanced \'[\' (encountered r_jmp, but found no closing bracket)"
        ((abortflag++))
      }
      # pop next char off stack
      local next_char=${bf_input::1}
      bf_input=${bf_input:1}
      # if next char is '[', we've encountered a nested loop and must increase depth counter
      [[ "$next_char" = "[" ]] && {
        ((depth++))
      }
      # if next char is ']', we've encountered closing brace and must decrease depth counter
      [[ "$next_char" = "]" ]] && {
        ((depth--))
      }
    done
  } || {
  ## else push stack
    loop_stack+=("$bf_input")
  }
}

l_jmp() {
  ((${tape[$pointer]:-0}!=0)) && {
  ## jump if not zero
    # if loop stack empty, we haven't encountered '[' yet.
    # according to brainfuck spec, we treat this as a fatal error
    ((${#loop_stack}==0)) && {
      print -u2 "FATAL: Unbalanced \']\' (encountered l_jmp, but found no closing bracket)"
      ((abortflag++))
    }
    # restore stack (revert to point of matching '[', thus completing l_jmp)
    bf_input="${loop_stack[-1]}"
  } || {
  ## else pop stack
    loop_stack[-1]=()
  }
}

## main

while true; do
  # if bf_input is empty and program not killed, return 0 (success)
  [[ -z "$bf_input" ]] && return 0
  # pop one char off input
  bf_working=${bf_input::1}
  bf_input=${bf_input:1}
  # instruction interpretation
  case $bf_working in
    ('<') pointer_decrement ;;
    ('>') pointer_increment ;;
    ('+') cell_increment ;;
    ('-') cell_decrement ;;
    ('.') print_cell ;;
    (',') stream_read ;;
    ('[') r_jmp ;;
    (']') l_jmp ;;
  esac
  ((abortflag>=1)) && return 1
done
